<?php

namespace AppBundle\Repository;

/**
 * FoodGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoodGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
