<?php

namespace AppBundle\Repository;

/**
 * NutrientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NutrientRepository extends \Doctrine\ORM\EntityRepository
{
}
