<?php

namespace AppBundle\Repository;

/**
 * NutrientFoodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NutrientFoodRepository extends \Doctrine\ORM\EntityRepository
{
}
