services:
#    test.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    import.csvtoarray:
        class: AppBundle\Service\ConvertCsvToArray